### ISSUE TITLE
Cannot generate report by command line

### ISSUE THREAD

**Issue by kanchi240** [sgoeschl/jmeter-sla-report#10]
Hi,

The detail error is below:
![image](https://user-images.githubusercontent.com/4908696/96560157-7fc4ff80-12f0-11eb-99f3-660babc661ae.png)

and my tools version is:

jmeter: 5.3
java: openjdk version "14.0.2" 2020-07-14

**Comment by sgoeschl** [comment]
Ooops, did not see the email - my bad.

Do you have JTL to reproduce the problem?

**Comment by kanchi240** [comment]
Hi, sgoeschl

I made a html file and then insert images and tables of test result generated by jenkins performance plugin for sending the report. If you have time, please see the attachment which is my newest JTL file, thanks a lot.
[jtlfiles.zip](https://github.com/sgoeschl/jmeter-sla-report/files/6242374/jtlfiles.zip)

**Comment by sgoeschl** [comment]
I will have a look at - it already looks like fun with all that non-ASCII characters :-)

**Comment by sgoeschl** [comment]
Hi @kanchi240, looking into the issue 

* The JTL files you created are actually CSV files and should have an "csv" extension to tell the parser to handle a CSV file
* The CSV files have a header row which makes perfect sense but are currently not supported - I'm looking into that

**Comment by sgoeschl** [comment]
![Uploading ISSUE-10.png…]()

**Comment by kanchi240** [comment]
@sgoeschl You are so kind, many thanks for your comment, I'll try it again.

**Comment by sgoeschl** [comment]
Release 1.0.5 so the latest and greatest stuff is on the "master" branch - please note that man class changed from  `org.apache.jmeter.extra.report.sla.Main` to `com.github.sgoeschl.jmeter.report.sla.Main`
