### ISSUE TITLE
Compile and Install Task

### ISSUE THREAD

**Issue by danielfcastro** [sgoeschl/jmeter-sla-report#4]
I found this plugin and download its source, but when I try to run mvn install a set of 6 tests run and 5 of them have a failed status.  So I try a mvn install -Dmaven.test.skip=true and it generates a jar file that I put into ext folder inside jmeter 2.11 but nothing new inside the menu.

Because of that I am assuming I am doing something wrong.
What is the procedure to compile and install?
And what is the minimum required version of JMeter?

**Comment by sgoeschl** [comment]
Documentation should be fine and the tests are improved to handle different operating systems and time zones
